const CATEGORIES = [
  { id: "elearning", label: "eLearning Authoring", color: "oklch(68% 0.14 230)", accent: "rgba(80,120,255,0.10)" },
  { id: "video", label: "Video-Based", color: "oklch(68% 0.14 160)", accent: "rgba(60,190,120,0.10)" },
  { id: "performance", label: "Performance Support", color: "oklch(68% 0.14 60)", accent: "rgba(220,160,60,0.10)" },
  { id: "live", label: "Live & ILT", color: "oklch(68% 0.14 20)", accent: "rgba(220,90,70,0.10)" },
  { id: "social", label: "Social & Experiential", color: "oklch(68% 0.14 300)", accent: "rgba(160,100,240,0.10)" },
  { id: "micro", label: "Microlearning & Mobile", color: "oklch(68% 0.14 195)", accent: "rgba(60,190,210,0.10)" },
  { id: "assessment", label: "Assessment & Credentialing", color: "oklch(68% 0.14 100)", accent: "rgba(100,200,80,0.10)" },
  { id: "ai", label: "AI-Powered", color: "oklch(68% 0.14 270)", accent: "rgba(200,120,255,0.10)" },
];

const SOLUTIONS = [
  // ── eLEARNING AUTHORING ──────────────────────────────────────────────────
  {
    id: "rise", category: "elearning", name: "Articulate Rise",
    tagline: "Responsive, scrollable eLearning built from pre-built blocks",
    effort: "Low–Medium", cost: "$$", update: "Easy",
    use_cases: ["Process overviews", "Onboarding modules", "System walkthroughs", "Knowledge refreshers", "Microlearning", "Pre-work for ILT/VILT", "Compliance refreshers"],
    pros: ["Rapid development; faster than traditional eLearning", "Fully responsive across desktop and mobile", "Clean, modern UI with no design skill required", "Easy to update without rebuilding", "Collaborative multi-author editing", "SCORM/xAPI compliant for LMS tracking", "Accessible: screen readers, keyboard navigation"],
    cons: ["Limited interactivity vs. Storyline — no complex branching", "Templated look can feel generic", "Less control over visual design", "Not ideal for skill-practice or deep scenario-based learning"],
  },
  {
    id: "storyline", category: "elearning", name: "Articulate Storyline",
    tagline: "Highly interactive, custom eLearning with branching and simulations",
    effort: "Medium–High", cost: "$$–$$$", update: "Moderate",
    use_cases: ["Software simulations", "Complex decision-making scenarios", "Skill practice", "Compliance training with assessment"],
    pros: ["Highly customizable — full control over design, interactions, and logic", "Complex branching, variables, and triggers", "Excellent for software simulations (screen recording + try mode)", "Advanced assessment and quiz engine", "Large user community with templates and tutorials", "SCORM and xAPI compliant"],
    cons: ["Steep learning curve for advanced features", "Desktop-only authoring (Windows preferred)", "40–100+ dev hours per finished hour of interactive content", "Mobile responsiveness requires extra consideration", "Can be over-engineered for simple informational content"],
  },
  {
    id: "captivate", category: "elearning", name: "Adobe Captivate",
    tagline: "Enterprise authoring for eLearning, VR, and software simulations",
    effort: "Medium–High", cost: "$$$", update: "Moderate–Difficult",
    use_cases: ["Software training", "360 image-based immersive learning", "Compliance modules", "Responsive multi-device content"],
    pros: ["Strong software simulation capabilities", "VR content creation without coding", "Responsive design using fluid boxes", "PowerPoint import and conversion", "Strong quiz and assessment features"],
    cons: ["Steepest learning curve of major authoring tools", "Expensive licensing", "Smaller user community than Articulate", "Can feel clunky compared to modern tools", "Inconsistent update history"],
  },
  {
    id: "sway", category: "elearning", name: "Microsoft Sway",
    tagline: "Free, web-based storytelling tool for quick informational content",
    effort: "Low", cost: "Free (M365)", update: "Easy",
    use_cases: ["Quick informational shares", "Newsletters", "Orientation overviews", "Internal communication", "Knowledge pages"],
    pros: ["Zero learning curve — drag and drop", "Already in Microsoft ecosystem", "Auto-designs content for polished look", "Easy sharing via link", "Embeds multimedia seamlessly"],
    cons: ["No tracking or assessment capability", "Very limited interactivity", "No SCORM/LMS integration", "Limited offline access", "Not suitable for formal training or structured learning"],
  },
  {
    id: "vyond", category: "elearning", name: "Vyond (Animated Video)",
    tagline: "Cloud-based animated explainer and scenario-based video creation",
    effort: "Medium", cost: "$$", update: "Easy–Moderate",
    use_cases: ["Concept explanations", "Soft-skill scenarios", "Change management messaging", "Culture and values content", "Microlearning videos"],
    pros: ["Engaging and memorable animation format", "No filming equipment, actors, or studio needed", "Consistent visual brand", "Quick iteration and editing", "Scenario-based storytelling without live actors"],
    cons: ["Can look cartoonish for serious topics", "Character and asset libraries can feel limiting", "Audio/voiceover still required", "Animation quality gap vs. professional studios"],
  },
  {
    id: "linkedin", category: "elearning", name: "LinkedIn Learning",
    tagline: "Thousands of pre-built courses on leadership, business, and tech",
    effort: "Low", cost: "Free (Enterprise License)", update: "Easy",
    use_cases: ["Leadership development", "Professional skill building", "Technology training", "Self-directed development", "Just-in-time learning"],
    pros: ["Large library of professionally produced courses", "Fast deployment — no internal development required", "Broad topics covered", "Learners can self-direct", "Integrates with many LMS platforms"],
    cons: ["Content is generic, not Penske-specific", "Limited alignment with internal processes", "Quality varies by instructor", "Learners may struggle to choose relevant courses", "Requires curation to align with priorities"],
  },

  // ── VIDEO ─────────────────────────────────────────────────────────────────
  {
    id: "synthesia", category: "video", name: "Synthesia",
    tagline: "AI avatar presenter videos from text scripts — no filming required",
    effort: "Low–Medium", cost: "$$", update: "Easy",
    use_cases: ["Process explainers", "Policy updates", "Onboarding welcome messages", "Multilingual content", "Standardized communications"],
    pros: ["Script to finished video in minutes without filming", "No equipment, talent scheduling, or studio needed", "Easy to update: change script and regenerate", "Multilingual support — dozens of languages", "Consistent presenter quality", "Team license already in place"],
    cons: ["AI avatars may feel impersonal for emotional topics", "Limited to presenter-style formats — not for hands-on demos", "Custom avatar creation adds cost", "Viewer trust in AI presenters still evolving"],
  },
  {
    id: "camtasia", category: "video", name: "Camtasia",
    tagline: "Screen recording and video editing for tutorials and demos",
    effort: "Medium", cost: "$$", update: "Moderate",
    use_cases: ["Software demos", "System walkthroughs", "How-to tutorials", "Recorded presentations with screen share"],
    pros: ["Widely used for screen capture and editing", "Built-in callouts, annotations, and zoom effects", "Professional-quality output", "One-time license option", "Supports interactive quizzes with SCORM"],
    cons: ["Requires time for editing, captioning, and polish", "Large file sizes for long recordings", "Learning curve for advanced features", "No real-time collaboration in editing", "Captions require extra effort"],
  },
  {
    id: "liveaction", category: "video", name: "Live-Action Video",
    tagline: "Professionally filmed video with full production quality",
    effort: "High", cost: "$$$–$$$$", update: "Difficult",
    use_cases: ["Leadership messages", "Safety demonstrations", "Customer-facing training", "Culture and values", "High-stakes procedural content"],
    pros: ["Highest production quality and credibility", "Highly engaging with real people and environments", "Can demonstrate physical tasks and environments", "Strong for safety and compliance", "Reusable across multiple channels"],
    cons: ["Most expensive option: equipment, actors, crew", "Longest development timeline", "Difficult and costly to update", "Requires scripting, storyboarding, location scouting", "SMEs may not be comfortable on camera"],
  },
  {
    id: "ugv", category: "video", name: "Smartphone / User-Generated Video",
    tagline: "Quick, informal video from SMEs or managers for peer knowledge sharing",
    effort: "Low", cost: "$", update: "Easy",
    use_cases: ["Quick tips", "Peer best practices", "Field demonstrations", "Manager messages", "Just-in-time troubleshooting"],
    pros: ["Extremely fast to produce and distribute", "Authentic and relatable", "No production team needed", "Easy to refresh and replace", "Captures tacit knowledge from SMEs", "Scalable — anyone can contribute"],
    cons: ["Inconsistent quality (lighting, audio, framing)", "May lack credibility for formal training", "No built-in tracking or assessment", "Storage and organization can become unwieldy", "Brand consistency challenges"],
  },
  {
    id: "panopto", category: "video", name: "Panopto (Video Platform)",
    tagline: "Enterprise video hosting, search, and delivery with analytics",
    effort: "Low (setup)", cost: "Enterprise", update: "Easy",
    use_cases: ["Video library management", "Recorded meetings", "Searchable video archives", "Live streaming events"],
    pros: ["Centralized video management and search", "Auto-captioning and transcription", "Analytics on viewership and engagement", "Integration with communication tools", "In-video spoken word search"],
    cons: ["Adds another platform for learners to navigate", "Content curation requires ongoing governance", "Quality still depends on source video", "May duplicate functionality of Teams or SharePoint"],
  },

  // ── PERFORMANCE SUPPORT ───────────────────────────────────────────────────
  {
    id: "jobaid", category: "performance", name: "Job Aid (PDF / Printed)",
    tagline: "Concise, task-specific reference used at the point of need",
    effort: "Low", cost: "$", update: "Easy",
    use_cases: ["Step-by-step procedures", "Quick reference for infrequent tasks", "Checklists", "Troubleshooting guides", "Safety reminders"],
    pros: ["Fastest solution to develop", "Used at the moment of need — true performance support", "No technology required for end user", "Easy to print and post at workstations", "Reduces cognitive load", "Low maintenance"],
    cons: ["Not suitable for complex or conceptual learning", "Can get lost, damaged, or ignored", "No tracking or completion data", "Version control challenges with printed copies", "Doesn't build deeper understanding"],
  },
  {
    id: "qrg", category: "performance", name: "Quick Reference Guide (QRG)",
    tagline: "2–4 page reference covering key workflows or decision criteria",
    effort: "Low–Medium", cost: "$", update: "Easy",
    use_cases: ["New hire reference packets", "System navigation guides", "Policy summaries", "Role-specific procedure collections"],
    pros: ["More comprehensive than a single job aid", "Covers multiple related tasks or decisions", "Portable and practical", "Good complement to formal training", "Easy to brand and standardize"],
    cons: ["Can become too long and go unused", "Maintenance burden grows with detail level", "Still no tracking or interactivity", "Requires good visual design to be scannable", "Risk of becoming a catch-all document"],
  },
  {
    id: "ipdf", category: "performance", name: "Interactive PDF / Digital Flipbook",
    tagline: "Polished multi-page PDF with clickable navigation and embedded links",
    effort: "Medium", cost: "$–$$", update: "Moderate",
    use_cases: ["Onboarding handbooks", "Program overviews", "Branded resource guides", "Leadership playbooks", "Stakeholder-facing deliverables"],
    pros: ["Professional, polished presentation", "Clickable table of contents and internal navigation", "Can embed links to videos and websites", "Flipbook format creates engaging digital reading experience", "No special software required for the reader"],
    cons: ["Higher design effort than a standard job aid", "Requires design software or flipbook platform", "Interactive elements can break across PDF readers", "Not ideal for frequently changing content", "Accessibility requires deliberate effort"],
  },
  {
    id: "onenote", category: "performance", name: "OneNote Repository",
    tagline: "Structured team knowledge base using Microsoft OneNote",
    effort: "Low–Medium", cost: "$", update: "Easy",
    use_cases: ["Team knowledge bases", "Meeting notes archives", "Project documentation", "Evolving reference libraries", "Collaborative content curation"],
    pros: ["Already in Microsoft ecosystem", "Flexible structure (notebooks > sections > pages)", "Supports multimedia content", "Real-time collaboration and sharing", "Searchable across all content", "Works offline with sync"],
    cons: ["Can become disorganized without governance", "No formal tracking or completion metrics", "Not designed as a formal learning tool", "Difficult to enforce version control", "Can become a content graveyard without ownership"],
  },
  {
    id: "sharepoint", category: "performance", name: "SharePoint / Knowledge Hub",
    tagline: "Enterprise intranet portal for organizing training resources and policies",
    effort: "Medium–High", cost: "$ (M365)", update: "Easy–Moderate",
    use_cases: ["Centralized training portals", "Policy libraries", "Department resource hubs", "Onboarding sites", "Document management"],
    pros: ["Enterprise-grade permissions and governance", "Powerful search and metadata capabilities", "Integration with Power Automate for workflows", "Professional appearance with modern templates", "Version control and document management built-in", "Scales across the organization"],
    cons: ["Requires SharePoint admin knowledge to set up well", "Complex to design intuitive navigation", "Content governance is essential — easily becomes cluttered", "User adoption can be a challenge", "Mobile experience can vary"],
  },
  {
    id: "powerapps", category: "performance", name: "Digital Checklist / Power Apps",
    tagline: "Mobile-accessible digital checklists and guided workflows with data capture",
    effort: "Low–Medium", cost: "$ (M365)", update: "Easy",
    use_cases: ["Safety inspections", "Equipment checks", "Onboarding task completion", "Quality audits", "Field procedures"],
    pros: ["Used at the point of work on mobile devices", "Captures completion data and timestamps", "Can include photos, signatures, conditional logic", "Reduces paper-based processes", "Integrates with Power Automate and SharePoint"],
    cons: ["Requires connectivity for real-time submission", "Setup requires technical skill", "Not a learning experience — more compliance/verification", "Can feel bureaucratic if overused", "Device dependency for frontline workers"],
  },

  // ── LIVE & ILT ───────────────────────────────────────────────────────────
  {
    id: "ilt", category: "live", name: "ILT: Classroom",
    tagline: "Traditional face-to-face facilitated training with activities and practice",
    effort: "High", cost: "$$$", update: "Easy–Moderate",
    use_cases: ["Leadership development", "Complex skill-building", "Safety certifications", "Team-building", "Hands-on equipment training"],
    pros: ["Highest engagement and interaction potential", "Facilitator can adapt in real time", "Builds relationships and peer learning networks", "Best for hands-on skill practice", "Immediate feedback and coaching", "Strong for emotionally complex topics"],
    cons: ["Most expensive per-learner delivery method", "Travel, logistics, and scheduling overhead", "Scalability is limited — one class at a time", "Quality can vary depending on facilitator", "Difficult to standardize across locations"],
  },
  {
    id: "vilt", category: "live", name: "Virtual ILT (VILT)",
    tagline: "Live, facilitator-led training via Teams/Zoom with interactive elements",
    effort: "Medium–High", cost: "$$", update: "Easy–Moderate",
    use_cases: ["Geographically dispersed teams", "Policy rollouts", "System training with live demo", "Discussion-based learning", "Soft skill development"],
    pros: ["Reaches dispersed audiences without travel", "Maintains live human interaction and facilitation", "Can be recorded for on-demand access later", "Interactive tools (polls, breakouts, chat) drive engagement", "More cost-effective than ILT at scale"],
    cons: ["Learner attention can be harder to maintain", "Technology issues can disrupt sessions", "Breakout rooms require careful design", "Less effective for hands-on physical skill practice", "Virtual fatigue is real"],
  },
  {
    id: "workshop", category: "live", name: "Workshop / Working Session",
    tagline: "Activity-driven sessions where participants solve problems and make decisions together",
    effort: "Medium", cost: "$$", update: "Easy",
    use_cases: ["Strategic planning", "Process improvement", "Team alignment", "Design thinking", "Problem-solving", "Action planning"],
    pros: ["Produces tangible outputs — plans, decisions, artifacts", "High engagement through active participation", "Builds team alignment and ownership", "Flexible — virtual or in-person", "Participants learn by doing"],
    cons: ["Requires skilled facilitation", "Outcomes depend heavily on group dynamics", "Can be difficult to scale", "Time-intensive for participants", "Less structured knowledge transfer than formal training"],
  },
  {
    id: "lunchandlearn", category: "live", name: "Lunch & Learn / Knowledge Share",
    tagline: "Informal 30–60 min sessions led by SMEs or team members",
    effort: "Low", cost: "$", update: "Easy",
    use_cases: ["Cross-functional awareness", "New tool introductions", "Best practice sharing", "Team culture building", "Emerging topic exploration"],
    pros: ["Minimal development effort", "Leverages internal expertise", "Builds culture of learning and knowledge sharing", "Low time commitment for attendees", "Can be recorded for broader reach"],
    cons: ["Attendance can be inconsistent", "Quality varies by presenter", "No formal assessment or accountability", "Can become stale without active curation", "Not a substitute for structured skill development"],
  },

  // ── SOCIAL & EXPERIENTIAL ─────────────────────────────────────────────────
  {
    id: "mentoring", category: "social", name: "Mentoring Program",
    tagline: "Structured pairing of experienced employees with mentees for guided development",
    effort: "Medium (program); Low (per interaction)", cost: "$", update: "Easy",
    use_cases: ["Leadership pipeline development", "New employee integration", "Career development", "Knowledge transfer from retiring workforce"],
    pros: ["Builds deep relationships and knowledge transfer", "Highly personalized development", "Develops both mentor and mentee", "Low direct cost — leverages existing talent", "Supports retention and engagement"],
    cons: ["Requires careful matching and program structure", "Quality depends heavily on mentor commitment", "Difficult to measure impact", "Can create dependency rather than independence", "Requires time investment from senior leaders"],
  },
  {
    id: "ojt", category: "social", name: "On-the-Job Training (OJT)",
    tagline: "Learning by doing under guidance — from informal shadowing to structured sign-offs",
    effort: "Medium (structured); Low (informal)", cost: "$", update: "Easy–Moderate",
    use_cases: ["Hands-on technical skills", "Equipment operation", "Route/site-specific procedures", "Role transitions"],
    pros: ["Learning happens in the real work context", "Immediate application of skills", "No classroom time needed", "Builds confidence through practice", "Trainer can provide real-time coaching", "Structured OJT ensures consistency"],
    cons: ["Quality depends heavily on the trainer", "Can perpetuate bad habits if trainers aren't consistent", "Productivity impact during training period", "Difficult to standardize without structure", "Informal OJT is essentially 'figure it out'"],
  },
  {
    id: "simulation", category: "social", name: "Simulation / Role-Play",
    tagline: "Structured practice in realistic but safe scenarios — in-session or standalone",
    effort: "Medium–High", cost: "$$–$$$", update: "Moderate–Difficult",
    use_cases: ["Sales conversations", "Difficult employee conversations", "Safety response drills", "Decision-making under pressure", "Leadership scenarios"],
    pros: ["Closest to real performance without real consequences", "Builds confidence through practice", "Reveals skill gaps that knowledge checks miss", "Highly engaging and memorable", "Can be facilitated in-person or virtually"],
    cons: ["Requires significant design effort for realism", "Some learners may feel uncomfortable with role-play", "Facilitator skill is critical", "Difficult to scale without technology", "Assessment is subjective without rubrics"],
  },

  // ── MICROLEARNING & MOBILE ────────────────────────────────────────────────
  {
    id: "micro", category: "micro", name: "Microlearning Modules (2–5 min)",
    tagline: "Bite-sized, single-objective learning nuggets for digital delivery",
    effort: "Low–Medium", cost: "$–$$", update: "Easy",
    use_cases: ["Knowledge reinforcement", "Spaced repetition", "Just-in-time refreshers", "Pre/post-training support", "Daily tips"],
    pros: ["Fits into busy schedules with minimal time away", "Higher completion rates than longer courses", "Easier to update and maintain", "Effective for knowledge retention through spaced repetition", "Mobile-friendly delivery", "Can be sequenced into learning paths"],
    cons: ["Not suitable for complex multi-step skill building", "Can feel fragmented without a larger learning architecture", "Easy to produce low-quality 'content snacks'", "Tracking many small modules creates LMS overhead", "Requires strong curation to avoid content sprawl"],
  },
  {
    id: "mobilepush", category: "micro", name: "Mobile Push / SMS Learning",
    tagline: "Learning prompts, tips, and micro-assessments delivered to mobile devices",
    effort: "Low", cost: "$–$$", update: "Easy",
    use_cases: ["Behavior reinforcement", "Safety reminders", "Post-training follow-up", "Spaced practice prompts", "Time-sensitive updates"],
    pros: ["Reaches learners where they already are", "Immediate delivery and visibility", "Great for reinforcement and habit building", "Low development effort per message", "Data on open rates and engagement"],
    cons: ["Message fatigue — easy to become noise", "Limited depth per interaction", "Requires opt-in and mobile device policies", "Not suitable for complex content", "Tracking learning outcomes is limited"],
  },
  {
    id: "podcast", category: "micro", name: "Podcast / Audio Learning",
    tagline: "Audio-based learning: interviews, narrated lessons, and SME conversations",
    effort: "Low–Medium", cost: "$–$$", update: "Easy–Moderate",
    use_cases: ["Leadership insights", "Industry trends", "Culture storytelling", "Commute-friendly content", "SME interviews", "Change communications"],
    pros: ["Consumed during commutes, walks, or downtime", "Low production cost compared to video", "Humanizing — voice creates connection", "Scalable content delivery", "Builds thought leadership internally", "Great for drivers and mobile workforce"],
    cons: ["No visual component — limited for procedural content", "Difficult to assess learning or comprehension", "Passive consumption — low interactivity", "Discovery and curation challenges", "Accessibility requires transcripts"],
  },

  // ── ASSESSMENT & CREDENTIALING ────────────────────────────────────────────
  {
    id: "quiz", category: "assessment", name: "Knowledge Assessment / Quiz",
    tagline: "Formal or informal assessments from pulse checks to certification exams",
    effort: "Low–Medium", cost: "$", update: "Easy",
    use_cases: ["Post-training validation", "Compliance verification", "Pre-assessment for placement", "Knowledge gap analysis"],
    pros: ["Objective measurement of knowledge", "Easy to administer at scale via LMS", "Data-driven insights on learning effectiveness", "Can be auto-graded for efficiency", "Supports compliance documentation"],
    cons: ["Measures knowledge, not performance", "May incentivize memorization over understanding", "Question quality determines assessment quality", "Test anxiety can skew results", "Doesn't capture on-the-job application"],
  },
  {
    id: "observation", category: "assessment", name: "Skill Observation / Competency Checklist",
    tagline: "Structured observation of learners performing actual job tasks against defined criteria",
    effort: "Medium", cost: "$", update: "Easy",
    use_cases: ["Equipment operation certification", "Safety compliance verification", "Customer interaction quality", "New hire proficiency validation"],
    pros: ["Measures actual performance, not just knowledge", "Provides coaching opportunity during observation", "Documents competency for compliance", "Identifies specific skill gaps", "High face validity — evaluates real work"],
    cons: ["Observer calibration is critical", "Time-intensive per learner", "Scheduling observations is logistically challenging", "Can create performance anxiety", "Scaling across locations requires standardization"],
  },
  {
    id: "badge", category: "assessment", name: "Digital Badge / Certification Program",
    tagline: "Verifiable digital credentials awarded upon completing defined learning paths",
    effort: "High (program design)", cost: "$$–$$$", update: "Moderate",
    use_cases: ["Career pathing", "Skill recognition", "Compliance certification", "Professional development milestones", "Talent marketplace enablement"],
    pros: ["Visible recognition that motivates learners", "Creates clear development pathways", "Supports internal mobility and talent marketplace", "Compliance tracking and audit documentation", "Builds a learning culture through achievement"],
    cons: ["Significant upfront design and governance effort", "Badge inflation can devalue the system", "Requires ongoing maintenance and content updates", "Technology platform needed (Credly, LMS integration)", "Can create 'check the box' behavior if not designed well"],
  },

  // ── AI-POWERED ────────────────────────────────────────────────────────────
  {
    id: "chatbot", category: "ai", name: "AI Coaching / Chatbot (Sage AI)",
    tagline: "Conversational AI for on-demand coaching, Q&A, and guided process navigation",
    effort: "Medium–High", cost: "$$–$$$", update: "Moderate",
    use_cases: ["Onboarding guidance", "Process navigation", "Just-in-time reference", "Scenario practice"],
    pros: ["Available 24/7 — no scheduling required", "Scales infinitely across learners", "Can personalize based on role or context", "Reduces repetitive questions to L&D and SMEs", "Data on common questions informs content strategy"],
    cons: ["Quality depends on training data and prompt engineering", "Can give incorrect or hallucinated answers", "Doesn't replace human connection for complex development", "Requires ongoing tuning and governance", "User trust and adoption can be slow"],
  },
  {
    id: "aicontent", category: "ai", name: "AI-Generated Content Assistance (Sage AI)",
    tagline: "Using generative AI to accelerate L&D content development and adaptation",
    effort: "Low (per asset)", cost: "$–$$", update: "Easy",
    use_cases: ["Accelerating content development", "Drafting facilitator guides", "Generating quiz questions", "Adapting content for different audiences", "Creating job aid drafts"],
    pros: ["Dramatically accelerates first-draft creation", "Scales content adaptation (role, level, language)", "Reduces SME time for initial content drafts", "Generates assessment questions from source material", "Enables rapid prototyping of learning solutions"],
    cons: ["Requires human review — outputs should be validated by SMEs", "Quality varies by prompt quality and source inputs", "Copyright and IP considerations", "Can produce generic or surface-level content", "Over-reliance may atrophy L&D design skills"],
  },
];

Object.assign(window, { SOLUTIONS, CATEGORIES });
